# Generated by Django 4.2.7 on 2023-11-01 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='receita',
            options={'verbose_name_plural': 'Receita'},
        ),
    ]
