# Generated by Django 4.2.7 on 2023-11-01 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_alter_categoria_options_alter_receita_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='receita',
            options={},
        ),
    ]
