# Generated by Django 4.2.7 on 2023-11-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_alter_categoria_options_alter_receita_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='imagem',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='receitas/'),
        ),
    ]
