# Generated by Django 4.2.7 on 2023-11-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0007_receita_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='usuario',
            new_name='user',
        ),
    ]
