# Generated by Django 4.2.7 on 2023-11-13 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0008_rename_usuario_receita_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='user',
            new_name='usuario',
        ),
    ]
